// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgchiokdqyakyodvnkbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnY2hpb2tkcXlha3lvZHZua2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTU4MzEsImV4cCI6MjA3NDM3MTgzMX0.l2wIQQTsCEkT0EkTwueIL6YdS2Ttkokcz0tXE4s6wdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});